name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        env-version: 
          - os: "ubuntu-latest"
            python: 3.9

    runs-on: ${{ matrix.env-version.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.env-version.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.env-version.python }}

      - name: setup
        run: |
          python -m pip install --upgrade pip
          pip3 install --upgrade click==8.0.2

      - name: install
        run: make install

      - name: test
        run: make test
